### ISSUE TITLE
The real issue

### ISSUE THREAD

**Issue by NitinNR** [fadeevab/18-lines-request-generator#1]
Will it over cross the server limit?
I mean that suppose a particular server can only process 50 requests per second then it can't handle 60 requests per second right?will this technique help in this case?

**Comment by fadeevab** [comment]
Hi @NitinNR, the client generates as many requests as it can regardless server capabilities, if the client generates too many requests and exceeds the server's limit it will most likely start to get server error on the new connections, e.g. 403 error, or even just 500, it depends on server implementation.

**Comment by NitinNR** [comment]
> Hi @NitinNR, the client generates as many requests as it can regardless server capabilities, if the client generates too many requests and exceeds the server's limit it will most likely start to get server error on the new connections, e.g. 403 error, or even just 500, it depends on server implementation.

Suppose the server has the daily quata for the requests will this technique over cross the quata?

**Comment by fadeevab** [comment]
I'm not sure I correctly understand your question, but this method can help you to generate huge number of requests which exceeds the quota of a server, as well as you can generate small number of requests not exceeding the quota of the server. It all depends on capabilities of your client comparing to "quota" of the server.
